[package]
name = "touying"
version = "0.1.0"
entrypoint = "lib.typ"
authors = ["OrangeX4", "Andreas Kr√∂pelin", "ntjess", "Enivex"]
license = "MIT"
description = "An object-oriented package for creating presentation slides in Typst."
repository = "https://github.com/touying-typ/touying"
exclude = ["examples"]