[package]
name = "touying"
version = "0.6.1"
entrypoint = "lib.typ"
authors = ["OrangeX4", "enklht", "Andreas Kr√∂pelin", "ntjess", "Enivex", "Pol Dellaiera", "pride7", "Coekjan"]
license = "MIT"
description = "A powerful package for creating presentation slides in Typst."
repository = "https://github.com/touying-typ/touying"
keywords = ["presentation", "pre", "slide", "slides", "lecture", "touying", "beamer", "talk"]
categories = ["presentation"]
exclude = ["examples"]
compiler = "0.12.0"